# Generated by Django 5.2.1 on 2025-06-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=50, unique=True, verbose_name='File Number')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Legal Name / Owner')),
                ('commercial_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Commercial Name')),
                ('pool_type', models.CharField(max_length=50, verbose_name='Type')),
                ('address', models.TextField(verbose_name='Address')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area (m²)')),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume (m³)')),
                ('approval_resolution_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Approval Resolution Number')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('state', models.CharField(choices=[('RES_EXPIRED', 'Resolution Expired'), ('RES_VALID', 'Resolution Valid')], default='RES_VALID', max_length=20, verbose_name='State')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expires On')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Last Inspection Date')),
                ('current_state', models.CharField(choices=[('HEALTHY', 'Healthy'), ('UNHEALTHY', 'Unhealthy')], default='HEALTHY', max_length=20, verbose_name='Current State')),
            ],
            options={
                'verbose_name': 'Pool',
                'verbose_name_plural': 'Pools',
                'db_table': 'pools',
            },
        ),
    ]
