# Generated by Django 5.2.1 on 2025-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('INSPECTOR', 'Inspector'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=20, verbose_name='role'),
        ),
    ]
